version: '3.1'

services:
  db_postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/db_data/
    volumes:
      - /home/endurance/docker_containers/db/postgres:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432

  db_mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - /home/endurance/docker_containers/db/mongodb/db_data:/data/db:Z
    ports:
      - 27017:27017
