version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/endurance/docker_containers/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    privileged: true
    network_mode: host

# /etc/letsencrypt/live/ha.skylark.cloud/fullchain.pem
# /etc/letsencrypt/live/ha.skylark.cloud/privkey.pem
