- id: '1674738119201'
  alias: Away From Home
  description: ''
  trigger:
  - platform: device
    device_id: 6909611cbcac1582def8d019a7da1bda
    domain: device_tracker
    entity_id: device_tracker.sushants_iphone
    type: leaves
    zone: zone.home
  condition: []
  action:
  - type: turn_off
    device_id: f6b869166a76b247a1e7bd0dfe6c4d23
    entity_id: switch.geyser_socket_1
    domain: switch
  - device_id: 6909611cbcac1582def8d019a7da1bda
    domain: mobile_app
    type: notify
    message: Stay Safe!
    title: Away from home
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off
    metadata: {}
  mode: single
- id: '1674738304634'
  alias: Home
  description: ''
  trigger:
  - platform: device
    device_id: 6909611cbcac1582def8d019a7da1bda
    domain: device_tracker
    entity_id: device_tracker.sushants_iphone
    type: enters
    zone: zone.home
  condition:
  - condition: time
    before: 07:00:00
    after: '17:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - device_id: 6909611cbcac1582def8d019a7da1bda
    domain: mobile_app
    type: notify
    message: Welcome
    title: Home
  - service: scene.turn_on
    target:
      entity_id: scene.lights
    metadata: {}
  mode: single
- id: '1674738784819'
  alias: Lights at 5:00PM
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition:
  - condition: device
    device_id: 6909611cbcac1582def8d019a7da1bda
    domain: device_tracker
    entity_id: device_tracker.sushants_iphone
    type: is_home
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights
    metadata: {}
  mode: single
- id: '1674738984239'
  alias: Dim Lights at 12:30AM
  description: ''
  trigger:
  - platform: time
    at: 00:30:00
  condition:
  - condition: device
    device_id: 56be783c21890511ff71ff10cf08340c
    domain: device_tracker
    entity_id: device_tracker.sm_g998b
    type: is_home
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_dim
    metadata: {}
  mode: single
- id: '1674739104775'
  alias: Turn off Geyser if Left On
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: f6b869166a76b247a1e7bd0dfe6c4d23
    entity_id: sensor.geyser_power
    domain: sensor
    below: 20
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: f6b869166a76b247a1e7bd0dfe6c4d23
    entity_id: switch.geyser_socket_1
    domain: switch
  - device_id: 56be783c21890511ff71ff10cf08340c
    domain: mobile_app
    type: notify
    message: Left On for too long
    title: Geyser Turned Off
  mode: single
- id: '1674739390124'
  alias: Send Geyser Notification
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: f6b869166a76b247a1e7bd0dfe6c4d23
    entity_id: switch.geyser_socket_1
    domain: switch
  condition: []
  action:
  - device_id: 56be783c21890511ff71ff10cf08340c
    domain: mobile_app
    type: notify
    message: Turned On
    title: Geyser
  - device_id: 6909611cbcac1582def8d019a7da1bda
    domain: mobile_app
    type: notify
    message: Turned On
    title: Geyser
  mode: single
- id: '1674761124182'
  alias: Test iPad Notification
  description: ''
  trigger:
  - type: plugged_in
    platform: device
    device_id: 56be783c21890511ff71ff10cf08340c
    entity_id: binary_sensor.sm_g998b_is_charging
    domain: binary_sensor
  condition: []
  action:
  - device_id: 95b272c97918e5a3f88f6df76a21eefc
    domain: mobile_app
    type: notify
    message: S21 Plugged In
    title: Charging
  mode: single
- id: '1674761378826'
  alias: Sunrise, Lights Off
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off
    metadata: {}
  mode: single
- id: '1674809077186'
  alias: Geyser Off - Turned On for too long
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: f6b869166a76b247a1e7bd0dfe6c4d23
    entity_id: switch.geyser_socket_1
    domain: switch
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
  - type: is_power
    condition: device
    device_id: f6b869166a76b247a1e7bd0dfe6c4d23
    entity_id: sensor.geyser_power
    domain: sensor
    below: 20
  action:
  - type: turn_off
    device_id: f6b869166a76b247a1e7bd0dfe6c4d23
    entity_id: switch.geyser_socket_1
    domain: switch
  - device_id: 56be783c21890511ff71ff10cf08340c
    domain: mobile_app
    type: notify
    message: 'Turned off - hot water present '
    title: Turned Geyser Off
  mode: single
- id: '1674893626932'
  alias: Turn On Repellent
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition:
  - condition: device
    device_id: 56be783c21890511ff71ff10cf08340c
    domain: device_tracker
    entity_id: device_tracker.sm_g998b
    type: is_home
  action:
  - type: turn_on
    device_id: b0a3c1628c92e0630dd7f256fc53d48d
    entity_id: switch.repellent_socket_1
    domain: switch
  mode: single
- id: '1674893686390'
  alias: Turn Off Repellent
  description: ''
  trigger:
  - platform: time
    at: 03:00:00
  condition: []
  action:
  - type: turn_off
    device_id: b0a3c1628c92e0630dd7f256fc53d48d
    entity_id: switch.repellent_socket_1
    domain: switch
  mode: single
