
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  external_url: https://ha.skylark.cloud

emulated_hue:
  listen_port: 80

wake_on_lan:

switch:
  - platform: wake_on_lan
    mac: 2c:f0:5d:70:2c:b9

http:
  # ssl_certificate: /config/ssl/fullchain.pem
  # ssl_key: /config/ssl/privkey.pem
  use_x_forwarded_for: true     # To ensure HA understands that client requests come via reverse proxy
  trusted_proxies:
    - 172.30.32.0/23            # In Home Assistant we need to add the Docker subnet
    - 127.0.0.1                 # Add the localhost IPv4 address
    - 122.175.56.144

zone:
  - name: Home
    latitude: 17.74732270010759
    longitude: 83.26318873613448
    radius: 200
    icon: mdi:account-multiple
