- id: '1674760011404'
  name: Lights On
  entities:
    light.wiz_rgbw_tunable_b96fe1:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 4000
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      friendly_name: WiZ RGBW Tunable B96FE1
      supported_features: 4
      state: 'on'
    light.wiz_rgbw_tunable_f1d4cc:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 4000
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      friendly_name: WiZ RGBW Tunable F1D4CC
      supported_features: 4
      state: 'on'
    light.wiz_rgbw_tunable_f20acc:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 4000
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      friendly_name: WiZ RGBW Tunable F20ACC
      supported_features: 4
      state: 'on'
    light.wiz_rgbw_tunable_f21380:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 4000
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      friendly_name: WiZ RGBW Tunable F21380
      supported_features: 4
      state: 'on'
  icon: mdi:ceiling-light-multiple
  metadata: {}
- id: '1674760224023'
  name: Lights Off
  entities:
    light.wiz_rgbw_tunable_b96fe1:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      friendly_name: WiZ RGBW Tunable B96FE1
      supported_features: 4
      state: 'off'
    light.wiz_rgbw_tunable_f1d4cc:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      friendly_name: WiZ RGBW Tunable F1D4CC
      supported_features: 4
      state: 'off'
    light.wiz_rgbw_tunable_f20acc:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      friendly_name: WiZ RGBW Tunable F20ACC
      supported_features: 4
      state: 'off'
    light.wiz_rgbw_tunable_f21380:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      friendly_name: WiZ RGBW Tunable F21380
      supported_features: 4
      state: 'off'
  icon: mdi:ceiling-light-multiple-outline
  metadata: {}
- id: '1674760296394'
  name: Lights Dim
  entities:
    light.wiz_rgbw_tunable_b96fe1:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      friendly_name: WiZ RGBW Tunable B96FE1
      supported_features: 4
      color_mode: color_temp
      brightness: 26
      color_temp_kelvin: 4000
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      state: 'on'
    light.wiz_rgbw_tunable_f1d4cc:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      friendly_name: WiZ RGBW Tunable F1D4CC
      supported_features: 4
      color_mode: color_temp
      brightness: 26
      color_temp_kelvin: 4000
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      state: 'on'
    light.wiz_rgbw_tunable_f20acc:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      friendly_name: WiZ RGBW Tunable F20ACC
      supported_features: 4
      color_mode: color_temp
      brightness: 26
      color_temp_kelvin: 4000
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      state: 'on'
    light.wiz_rgbw_tunable_f21380:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      friendly_name: WiZ RGBW Tunable F21380
      supported_features: 4
      color_mode: color_temp
      brightness: 26
      color_temp_kelvin: 4000
      color_temp: 250
      hs_color:
      - 26.812
      - 34.87
      rgb_color:
      - 255
      - 205
      - 166
      xy_color:
      - 0.421
      - 0.364
      state: 'on'
  icon: mdi:light-recessed
  metadata: {}
